# config/config.yaml

defaults:
  - override hydra/job_logging: disabled  # Optional: disable hydra logs

seed: 42
data:
  file_path: "/Volumes/Marsupium/marathon.hdf5"
  obs_keys: ["image", "velocity", "command"]
  act_keys: ["location"]
  obs_horizon: 1
  act_horizon: 5
  gap: 5
  obs_stride: 1
  act_stride: 5
  val_ratio: 0.2
  batch_size: 64
  num_workers: 4

model:
  backbone: "resnet34"
  pretrained: False
  steps: 5
  commands: 5

train:
  epochs: 10
  lr: 0.001
  use_compile: False
  save: True
  epoch_save: False
  use_weighted_loss: True

wandb:
  project: "image-policy"
  name: "image_net_weighted_loss"
  log: True
